
name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: bash ./buildAllPlatforms.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: bin/*

      - name: Release
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files:
            bin/*
